<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebApplication24._Default" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">




    <asp:Label Text="TEXTO" runat="server"></asp:Label>
    <asp:TextBox ID="txtuno" runat="server" ClientIDMode="Static"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" Text="Button" OnClick="Button1_Click" OnClientClick="return clickclient()" />
    <asp:RequiredFieldValidator ControlToValidate="txtuno" ErrorMessage="Requerido" runat="server"></asp:RequiredFieldValidator>
    <telerik:RadGrid runat="server" 
        OnInit="rgrd_Init" 
        OnItemDataBound="rgrd_ItemDataBound" 
        OnItemCreated="rgrd_ItemCreated" 
        RenderMode="Lightweight" 
        ID="rgrd" 
        ClientIDMode="Static" 
        AllowFilteringByColumn="True" 
        AllowPaging="True" 
        AllowSorting="True" 
        Culture="es-ES" 
        ShowGroupPanel="True" 
        AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" AllowCustomPaging="False">
        <MasterTableView AutoGenerateColumns="false" DataKeyNames="">
            <Columns>
                <telerik:GridBoundColumn HeaderText="Cabecera" DataField="Name"></telerik:GridBoundColumn>
                <telerik:GridBoundColumn HeaderText="Cabecera" DataField="Age"></telerik:GridBoundColumn>
            </Columns>
        </MasterTableView>
        <ClientSettings AllowDragToGroup="true"></ClientSettings>
        <MasterTableView GroupLoadMode="Client"></MasterTableView>
        <FilterMenu>
            <CollapseAnimation Type="InOutQuint" Duration="200" />
        </FilterMenu>
    </telerik:RadGrid>

     <%-- <PagerTemplate>
                <asp:LinkButton ID="LinkButton1" runat="server"></asp:LinkButton>
                <asp:LinkButton ID="LinkButton2" runat="server"></asp:LinkButton>
            </PagerTemplate>--%>
    <script>

        function clickclient() {



            alert($("#txtuno").val());
            if (confirm("se envia o no")) {
                return true;
            }
            return false;
        }
    </script>
</asp:Content>
